steps:
  - name: 'gcr.io/cloud-builders/npm'
    args: [ 'ci' ]
  - name: 'debian'
    args: [ 'bash', './preBuild.sh' ]
    env:
      - '___APIURL___=$_APIURL'
      - '__ENV__=$_ENV'
      - '__SENTRY_DSN__=$_SENTRY_DSN'
  - name: 'gcr.io/cloud-builders/npm'
    args: [ 'run', 'build' ]
  - name: 'gcr.io/cloud-builders/gsutil'
    args: [ '-m', 'rsync', '-r', '-d', 'cah/', 'gs://$_GS_BUCKET' ]
    dir: 'dist/'
